### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by riouxr** [joshuaKnauber/bpy-chat-gpt#1]
Hi! I get this when I try to load the addon in 3.3 or 3.4:

Traceback (most recent call last):
  File "/Applications/Blender3.4.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/riouxr/Library/Application Support/Blender/3.4/scripts/addons/bpy_chat_gpt/__init__.py", line 14, in <module>
    import requests
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/utils.py", line 28, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by joshuaKnauber** [comment]
Could you check if the requests package is installed?

Go into blender -> scripting workspace -> console in the bottom left:
Run `import requests`

If this doesn't throw an error that means it's installed

**Comment by riouxr** [comment]
I get this:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/utils.py", line 28, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by joshuaKnauber** [comment]
Try downloading the zip (from the main page, not the releases) and installing that. This uses a different package now so hopefully that will fix the issue

**Comment by riouxr** [comment]
That's what I did. I clicked on the release button and it brought me to another page.

**Comment by joshuaKnauber** [comment]
Yes, I just pushed an update which is not under releases yet. Try downloading and installing that again

**Comment by riouxr** [comment]
Seems to be working now. Thank you so much! I use ChatGTP with Blender on a daily basis

**Comment by riouxr** [comment]
So I don't get any error messages but I don't see the prompt area in the text editor.

**Comment by joshuaKnauber** [comment]
In the npanel?

**Comment by riouxr** [comment]
Oh yeah! Now I get this when I try something:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

I did put the API key in the add-on's prefs

**Comment by riouxr** [comment]
No, when I press play

**Comment by riouxr** [comment]
Any idea? :-)
